python train.py \
--not_sweep \
--batch_size 1 \
--gradient_accumulation_steps 2 \
--num_epochs 5 \
--net_name test_varnet \
--data_path_train ../Data/train/ \
--data_path_val ../Data/val/ \
--lr 1e-3 \
--cascade 1 \
--chans 9 \
--pools 4 \
--sens_chans 4 \
--sens_pools 4 \
--input_key kspace \
--target_key image_label \
--max_key max \
--seed 430