python train_pmr.py \
--not_sweep \
--batch_size 1 \
--gradient_accumulation_steps 2 \
--num_workers 4 \
--num_epochs 5 \
--net_name test_promptmr \
--model_name utils.model.promptmr.PromptMR \
--data_path_train ../Data/train/ \
--data_path_val ../Data/val/ \
--lr 3e-4 \
--num_cascades 1 \
--num_adj_slices 1 \
--n_feat0 12 \
--feature_dim 16 20 24 \
--prompt_dim 4 8 12 \
--sens_n_feat0 4 \
--sens_feature_dim 6 8 10 \
--sens_prompt_dim 2 4 6 \
--len_prompt 2 2 2 \
--prompt_size 64 32 16 \
--n_enc_cab 2 3 3 \
--n_dec_cab 2 2 3 \
--n_skip_cab 1 1 1 \
--n_bottleneck_cab 3 \
--n_buffer 0 \
--n_history 0 \
--no_use_ca True \
--learnable_prompt False \
--adaptive_input False \
--use_sens_adj False \
--compute_sens_per_coil False \
--input_key kspace \
--target_key image_label \
--max_key max \
--seed 430 \
# --restart_from_checkpoint ../result/test_promptmr/checkpoints/0707_165655-9zbeok11/best_model.pt \
# --continue_lr_scheduler True